### ISSUE TITLE
Tutorial Comments

### ISSUE THREAD

**Issue by cmtognarina** [lokeshgupta1981/Kafka-Tutorials#1]
Thank you very much for your article series.  Just a couple of things that I encountered while attempting the steps in the tutorial (up through the third article).  I wanted to mention them in case it might help someone else.

Environment:
Windows 10
JDK 11
Spring-boot 2.3.5
Spring Initializer Dependencies
  Spring for Apache Kafka
  Spring Web
  Spring for Apache Kafka Streams
  Spring Cloud Stream
Zookeeper (separate install) apache-zookeeper-3.6.2-bin
Kafka kafka_2.13-2.6.0

Attempting to start zookeeper/kafka error:  Line too long
>> Shorten windows directory path where zookeeper and kafka were unzipped (advised to not have spaces in path either)

application.yaml file error when attempting to POST message to the consumer:
2020-11-07 18:33:20.848 ERROR 33236 --- [nio-9000-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.apache.kafka.common.errors.SerializationException: Can't convert value of class java.lang.String to class org.apache.kafka.common.serialization.ByteArraySerializer specified in value.serializer] with root cause
java.lang.ClassCastException: class java.lang.String cannot be cast to class [B (java.lang.String and [B are in module java.base of loader 'bootstrap')
        at org.apache.kafka.common.serialization.ByteArraySerializer.serialize(ByteArraySerializer.java:19) ~[kafka-clients-2.5.1.jar:na]
        at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62) ~[kafka-clients-2.5.1.jar:na]
        at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:902) ~[kafka-clients-2.5.1.jar:na]
        at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:862) ~[kafka-clients-2.5.1.jar:na]
. . . 

application.yaml file is mentioned in article, but I kept it as default name application.properties and the contents,
instead of being an indented tree structure, were modified to be flat instead because I was seeing errors in eclipse UI
(also note change from producer StringDeserializer to StringSerializer class, very important):
server.port: 9000
spring.kafka.consumer.bootstrap-servers: localhost:9092
spring.kafka.consumer.group-id: group-id
spring.kafka.consumer.auto-offset-reset: earliest
spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.bootstrap-servers: localhost:9092
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer

Zookeeper and Kafka config-related file changes that I made which seemed to help as well:
>> server.properties
log.dirs=../logs

>> zoo.cfg
dataDir=./../data
maxCnxns=2 (warning occurs if default of 0 is left in place)

Mr. Biswas's excellent article here was extremely helpful in resolving the issues I encountered:  https://towardsdatascience.com/running-zookeeper-kafka-on-windows-10-14fc70dcc771

**Comment by lokeshgupta1981** [comment]
Thanks for sharing.
